
"""Test revision

Revision ID: 5d963bc05296
Revises: None
Create Date: 2025-04-09 10:42:42.147697
"""

# revision identifiers, used by Alembic.
revision = '5d963bc05296'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
